import type { Metadata } from "next";
import "./globals.css";
import "./index.css";

// Import fonts from Google Fonts
import { Barlow_Condensed, Bellefair } from "next/font/google";
import Navbar from "./components/layout/Navbar";

const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-barlow-condensed",
  display: "swap",
});

const bellefair = Bellefair({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bellefair",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Space Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={``}>
      <body className={`${barlowCondensed.variable} ${bellefair.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}